language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  matrix:
    - TESTBENCH_VERSION="3.0.*"
    - TESTBENCH_VERSION="3.1.*"
    - TESTBENCH_VERSION="3.2.*"
    - TESTBENCH_VERSION="3.3.*"
    - TESTBENCH_VERSION="3.4.*"
    - TESTBENCH_VERSION="3.5.*"

before_script:
  - travis_retry composer self-update
  - travis_retry composer require orchestra/testbench:${TESTBENCH_VERSION} --dev --no-interaction

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
