language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - PHPUNIT_VERSION="~5.4"
  matrix:
    - TESTBENCH_VERSION="3.0.*"
    - TESTBENCH_VERSION="3.1.*"
    - TESTBENCH_VERSION="3.2.*"
    - TESTBENCH_VERSION="3.3.*"
    - TESTBENCH_VERSION="3.4.*"
    - TESTBENCH_VERSION="3.5.*" PHPUNIT_VERSION="~6.0" PHP_MIN_VERSION="7.0"

before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} < ${PHP_MIN_VERSION} ]]; then phpenv global ${PHP_MIN_VERSION}; fi
  - composer self-update
  - travis_retry composer require orchestra/testbench:${TESTBENCH_VERSION} phpunit/phpunit:${PHPUNIT_VERSION} --no-interaction

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
